"""add telemetry table

Revision ID: 829cdde0d3ff
Revises: 9ca960e64720
Create Date: 2026-06-29 15:06:09.076800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '829cdde0d3ff'
down_revision: Union[str, None] = '9ca960e64720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('throttle', sa.Integer(), nullable=True),
    sa.Column('brake', sa.Integer(), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('n_gear', sa.Integer(), nullable=True),
    sa.Column('drs', sa.Integer(), nullable=True),
    sa.CheckConstraint('brake IS NULL OR brake BETWEEN 0 AND 100', name='ck_telemetry_brake_range'),
    sa.CheckConstraint('speed IS NULL OR speed >= 0', name='ck_telemetry_speed_non_negative'),
    sa.CheckConstraint('throttle IS NULL OR throttle BETWEEN 0 AND 100', name='ck_telemetry_throttle_range'),
    sa.ForeignKeyConstraint(['driver_number'], ['drivers.driver_number'], ),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_key', 'driver_number', 'date', name='uq_telemetry_session_driver_date')
    )
    op.create_index('ix_telemetry_date', 'telemetry', ['date'], unique=False)
    op.create_index('ix_telemetry_session_driver', 'telemetry', ['session_key', 'driver_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_session_driver', table_name='telemetry')
    op.drop_index('ix_telemetry_date', table_name='telemetry')
    op.drop_table('telemetry')
    # ### end Alembic commands ###
