"""add stints table

Revision ID: a3f13bf73c71
Revises: 4eb2d85b8e3f
Create Date: 2026-06-29 23:47:23.906087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f13bf73c71'
down_revision: Union[str, None] = '4eb2d85b8e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('stint_number', sa.Integer(), nullable=False),
    sa.Column('compound', sa.String(), nullable=True),
    sa.Column('lap_start', sa.Integer(), nullable=False),
    sa.Column('lap_end', sa.Integer(), nullable=True),
    sa.Column('tyre_age_at_start', sa.Integer(), nullable=False),
    sa.CheckConstraint('lap_start > 0', name='ck_stints_lap_start_positive'),
    sa.CheckConstraint('stint_number > 0', name='ck_stints_stint_number_positive'),
    sa.CheckConstraint('tyre_age_at_start >= 0', name='ck_stints_tyre_age_non_negative'),
    sa.ForeignKeyConstraint(['driver_number'], ['drivers.driver_number'], ),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_key', 'driver_number', 'stint_number', name='uq_stints_session_driver_stint')
    )
    op.create_index('ix_stints_session_driver', 'stints', ['session_key', 'driver_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stints_session_driver', table_name='stints')
    op.drop_table('stints')
    # ### end Alembic commands ###
