"""initial schema

Revision ID: f218a6a6c57e
Revises: 
Create Date: 2026-06-29 13:05:07.371980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f218a6a6c57e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('circuit_key', sa.Integer(), nullable=False),
    sa.Column('circuit_short_name', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('country_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('circuit_key')
    )
    op.create_table('constructors',
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('team_colour', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('team_name')
    )
    op.create_table('seasons',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('constructor_standings',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_name'], ['constructors.team_name'], ),
    sa.ForeignKeyConstraint(['year'], ['seasons.year'], ),
    sa.PrimaryKeyConstraint('year', 'team_name')
    )
    op.create_table('drivers',
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('broadcast_name', sa.String(), nullable=True),
    sa.Column('name_acronym', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('headshot_url', sa.String(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_name'], ['constructors.team_name'], ),
    sa.PrimaryKeyConstraint('driver_number')
    )
    op.create_table('races',
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('meeting_key', sa.Integer(), nullable=True),
    sa.Column('circuit_key', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.Column('session_name', sa.String(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['circuit_key'], ['circuits.circuit_key'], ),
    sa.ForeignKeyConstraint(['year'], ['seasons.year'], ),
    sa.PrimaryKeyConstraint('session_key')
    )
    op.create_table('driver_standings',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_number'], ['drivers.driver_number'], ),
    sa.ForeignKeyConstraint(['year'], ['seasons.year'], ),
    sa.PrimaryKeyConstraint('year', 'driver_number')
    )
    op.create_table('laps',
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('lap_duration', sa.Float(), nullable=True),
    sa.Column('duration_sector_1', sa.Float(), nullable=True),
    sa.Column('duration_sector_2', sa.Float(), nullable=True),
    sa.Column('duration_sector_3', sa.Float(), nullable=True),
    sa.Column('i1_speed', sa.Integer(), nullable=True),
    sa.Column('i2_speed', sa.Integer(), nullable=True),
    sa.Column('st_speed', sa.Integer(), nullable=True),
    sa.Column('is_pit_out_lap', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_number'], ['drivers.driver_number'], ),
    sa.ForeignKeyConstraint(['session_key'], ['races.session_key'], ),
    sa.PrimaryKeyConstraint('session_key', 'driver_number', 'lap_number')
    )
    op.create_table('pit_stops',
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('pit_duration', sa.Float(), nullable=True),
    sa.Column('stop_duration', sa.Float(), nullable=True),
    sa.Column('lane_duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['driver_number'], ['drivers.driver_number'], ),
    sa.ForeignKeyConstraint(['session_key'], ['races.session_key'], ),
    sa.PrimaryKeyConstraint('session_key', 'driver_number', 'lap_number')
    )
    op.create_table('results',
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('number_of_laps', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('dnf', sa.Boolean(), nullable=False),
    sa.Column('dns', sa.Boolean(), nullable=False),
    sa.Column('dsq', sa.Boolean(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('gap_to_leader', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['driver_number'], ['drivers.driver_number'], ),
    sa.ForeignKeyConstraint(['session_key'], ['races.session_key'], ),
    sa.PrimaryKeyConstraint('session_key', 'driver_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('pit_stops')
    op.drop_table('laps')
    op.drop_table('driver_standings')
    op.drop_table('races')
    op.drop_table('drivers')
    op.drop_table('constructor_standings')
    op.drop_table('seasons')
    op.drop_table('constructors')
    op.drop_table('circuits')
    # ### end Alembic commands ###
