"""add starting grids table

Revision ID: f6aa2dc5ceb9
Revises: a3f13bf73c71
Create Date: 2026-06-30 00:30:41.850106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6aa2dc5ceb9'
down_revision: Union[str, None] = 'a3f13bf73c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starting_grids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('grid_position', sa.Integer(), nullable=False),
    sa.Column('qualifying_lap_duration', sa.Float(), nullable=True),
    sa.CheckConstraint('grid_position > 0', name='ck_starting_grids_position_positive'),
    sa.ForeignKeyConstraint(['driver_number'], ['drivers.driver_number'], ),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_key', 'driver_number', name='uq_starting_grids_session_driver')
    )
    op.create_index('ix_starting_grids_session_key', 'starting_grids', ['session_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_starting_grids_session_key', table_name='starting_grids')
    op.drop_table('starting_grids')
    # ### end Alembic commands ###
